### ISSUE TITLE
Values of 0 in CSS don't need units

### ISSUE THREAD

**Issue by griffinlacek** [dipu0243/prj-rev-bwfs-tea-cozy#3]
Tiny thing here, but values of 0 in CSS don't need units and a CSS linter will raise a warning about it. It doesn't affect anything, but it's a good practice to not include them! Here's a few spots where you have units attached to 0.

https://github.com/dipu0243/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L15
https://github.com/dipu0243/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L53
https://github.com/dipu0243/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L70

**Comment by dipu0243** [comment]
I will keep this in mind.
